name: heysheet
region: nyc

services:
  - name: backend
    source_dir: backend
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    git:
      branch: main
      repo_clone_url: https://github.com/FGonzales-Dev/heysheet.git
    # Bind to DO's injected $PORT (not hardcoded 8000)
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    http_port: 8000
    routes:
      - path: /api
    envs:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: ALLOWED_HOSTS
        value: ${APP_DOMAIN}
      - key: CORS_ALLOWED_ORIGINS
        value: ${APP_URL}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: "your-secret-key-here"
      - key: GOOGLE_SHEETS_CREDENTIALS
        type: SECRET
        value: "your-credentials-here"
      - key: GROQ_API_KEY
        type: SECRET
        value: "your-api-key-here"

  - name: frontend
    source_dir: frontend
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    git:
      branch: main
      repo_clone_url: https://github.com/FGonzales-Dev/heysheet.git
    build_command: npm ci && npm run build
    # Serve the built Vite app on the DO-injected $PORT
    run_command: npx serve -s dist -l $PORT
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api
        scope: BUILD_TIME

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"
